### ISSUE TITLE
A few "scary" questions...

### ISSUE THREAD

**Issue by RationalCoding** [Chat-Wane/LSEQTree#13]
I'm somewhat new to CDRT's, and I was hoping you could give me an insight into how to use this library. 

1. Is the unique identifier used for `.applyInsert` the same as the one inside the couple created by the remote `.insert`? Or should it be generated in some other way?

```
var lseq = require("lseqtree")

var a = new lseq(0)
var b = new lseq(1)

var ei = a.insert('A', 0)
var index = b.applyInsert(ei._e, ei._i) // <-- Correct?
```

2. Am I correct in assuming the index returned by `.applyInsert` is incremented by 1 because the "Begin" virtual leaf is always at index 0? The above example sets `index` to `1`, even though intuition would have 'A' be inserted at index 0.

3. How do I create a human-readable text document from the tree? In the other direction, is there a more efficient way to generate a tree from an existing document than just doing "Insert" for every character? 

Thanks for your patience, looking forward to any advice you can provide.

**Comment by RationalCoding** [comment]
Also, is there any way to make the indexes by line/column instead of absolute offset?

**Comment by Chat-Wane** [comment]
1. Your snippet is correct. 

2. I think (it was a long time ago) that you are again correct.

   Identifiers are generated between two other identifiers. Consequently, the tree is initialized with two hidden identifiers: identifier_min and identifier_max. Thus, < " " , identifier_min> takes Index 0 from start.

   I agree that the intuition would have 'A' inserted at index 0. At the time, I considered it as a shared structure without considering its usage. The indexes are the indexes of the "flattened" version of the tree. If I reworked it, I would probably switch to the behavior you mentioned.

3. The "scary" question! I wrote a [decentralized editor](https://github.com/Chat-Wane/CRATE) using [ace](https://ace.c9.io) for the GUI but you have other options such as [quill.js](https://quilljs.com). 
   > How do I create a human-readable text document from the tree?

   By default, when the user types a character, the editor will automatically print it. Your job is to catch this event and create an identifier depending on the insertion index in the document.

   Then, you have to send it to all members, i.e., a broadcast protocol is required, hence a membership protocol is required. When they receive the message, they must order the operations depending on the order these operations were generated, i.e., a form of causality tracking is required. (I leave this paragraph undetailled but I could detail more if you are interested)
   
   When the operation is "causally ready" to be integrated, you apply the operation to the tree structure which will give you an index. You map this with the GUI (commonly using patches). 
   > In the other direction, is there a more efficient way to generate a tree from an existing document than just doing "Insert" for every character?
   
   Like ```a.insert('This is the document.', 0)``` ?

   It is possible. Instead of generating an identifier for each character, you could generate an identifier for a string. [LogootSplit](https://hal.inria.fr/hal-00903813/document) does that. LSEQTree does not implement it though. In this approach, you have to be careful and split the strings when need be, e.g., ```a.insert('whole ' 12)``` splits ```This is the document``` in ```This is the ``` and ```document.``` resulting in ```This is the whole document.```. This is a trade-off, for you generate less identifiers (gain in CPU and memory) but when splits happen it becomes more costly. In practice, it is probably a significant improvement.

4. I don't think there is any way. You could instantiate 1 LSEQTree per line but that would not be good... With ace, there is a function that converts line/column to absolute offset, but I didn't check its complexity.

**Comment by RationalCoding** [comment]
Awesome answers, just a few clarifications...

2. The behavior is fine (and probably more "technically correct"), I just wanted to ensure my understanding was correct.

3. By "order the operations depending on the order these operations were generated", you mean that operations originating from the same site must be ordered, right? You don't mean some kind of global causality (which I thought was impossible?). ie) All of Alice's inserts are in order relative to Alice's other inserts, but maybe not relative to Bob's. `A1 -> A2 -> B1`  is just as valid as `A1 -> B1 -> A2`

I'll take a closer look at CRATE, seems to be the best place to start.

As for multiple character inserts... Logootsplit looks good, but doesn't Logoot have an issue with unbounded identifiers? I might be wrong, but I was under the assumption that LSEQ was an improvement (sublinear memory growth vs linear). Or is the difference insignificant in practice?

4. I figured out that I can convert line/ch to offset (and back) by keeping track of the newline characters in the document and moving these indexes when I insert/delete. Seems pretty fast with binary search and isn't limited to any editor implementation. So that should be fine.

Thanks again.

**Comment by Chat-Wane** [comment]
3. Here you choose the causality tracking mechanism that fits best the scale of your system  and the desired user experience.
- scale of the system: with 10 members you can afford to send the full version vector with each operation; with 100 members it is not practicable)
- user experience: with a version vector you can order all operations, thus if Alice types ```H``` , Bob receives it and types ```i```, Carol receives the later but since she did not yet receive ```H```, she cannot integrate ```i``` which is nice because the insertion of ```i``` only makes sense if the ```H``` exists. Also, the removal of a particular character always follows its insertion by design.   However, if you cannot afford the full version vector, you can only track a subset of required operations before integration. Here, it is up to you. In Crate, I chose to integrate all insertions as soon as they arrive (when Carol receives ```i``` she integrates it immediately without waiting for the ```H```) and removals wait for their respective insertion. But you could put additional constraints on insertion, eg wait for the insertion that precedes (in the document) the current one (```i```'s integration follows ```H```).

> Logoot have an issue with unbounded identifiers?

They are bounded but grow linearly. They may grow slowly --still linearly-- depending on the insertions order and positions.  

> Logootsplit looks good, but doesn't Logoot have an issue with unbounded identifiers?

Logoot has the aforementioned issue, but the "Split" part is an orthogonal improvement. Even though LogootSplit as a whole is introduced like a new CRDT, Logoot and Split are disjoint. Logoot provides identifiers, and Split allows the CRDT to work directly on strings. LSeqSplit could exist and it would benefit from both improvements.

> Or is the difference insignificant in practice?
It is difficult to answer precisely to this question, for it depends of the documents (positions of insertion and number of insertions), and the configuration of each approach. Since the space complexity of identifiers are different, there is not an equivalent configuration between Logoot and LSeq that would work for any document.

Since LSeq has a better complexity, it is "safer" when the size of the document grows. Plus, you can start with small identifiers.

4. Great!

You are welcome.
